### ISSUE TITLE
KInova PI or JAco robotical arm 

### ISSUE THREAD

**Issue by AsmaRoshaan** [Kinovarobotics/Extra_code_examples_Jaco2arm#1]
Hi
I am having an issue related to the jaco arm drivers. I installed jaco arm 2 on windows 10. It came with the device name "kinova pi (chinese words)" and drivers installation had no issue. Commands worked perfectly fine using matlab 2017b.
I installed that same jaco arm 2 on the second port. It installed with a name " Jacp robotical arm" using jacosoft drivers. Drivers got installed but matlab code is not working.Robot got connected but nothing is happening. Its not taking any values from robot neither send any command to robot.
WHY IS THAT ? It works only when " kinova pi" driver is installed on all the ports.
The problem is I want to use the same robot on windows 8 and it doesnot take any other driver except jacosot service drivers and device name comes as " jaco robotical arm" and it gets connect but its usefull. because it doesn't execute any command without giving any error. Can you tell me what is the problem????

**Comment by samuelhovington** [comment]
I think you post your question in another directory, am I right? Were you able to install the drivers properly?

**Comment by AsmaRoshaan** [comment]
Yes. Actually It was a problem that drivers doesn't support 32 bit windows. so I had to connect the robotic arm to 32 bit with Ethernet.
